# Makefile for Linux samples code
obj-$(CONFIG_TINNO_PERSO_SENSORS)   += perso_sensor/

# product device info
obj-$(CONFIG_TINNO_PRODUCT_INFO)    += dev_info/

# fingerprint.
obj-y                               += fingerprint/


